### ISSUE TITLE
正则表达式测试工具

### ISSUE THREAD

**Issue by HatsuneMiku030** [fissssssh/dev-tools#4]
实现一个正则表达式测试工具，可以输入正则表达式和测试文本，并且可观察匹配后的结果。

期望：
- 可以输入多行测试文本，可一次性测试所有测试文本。
- 增加一个大写入文本框，将粘贴进此文本框的内容，更具换行符、自定义标识符对此粘贴文本进行一次性切分，自动填充为多个测试文本供正则表达式测试。

**Comment by fissssssh** [comment]
Completed with commit bf2f8d57e6a760de77f02f59bb5984d068272533
